//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Notas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CursoModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CursoModel()
        {
            this.Llevas = new HashSet<LlevaModel>();
        }
    
        public string siglas { get; set; }
        public string nombre { get; set; }
        public Nullable<int> notaCCQT { get; set; }
        public string notasTareas { get; set; }
        public string notasComprobaciones { get; set; }
        public string notasExamenesCortos { get; set; }
        public string notasClases { get; set; }
        public Nullable<int> participacionForos { get; set; }
        public Nullable<int> notainvestigacion { get; set; }
        public Nullable<int> notaPlanificacion { get; set; }
        public Nullable<int> notaEjecucionReporte { get; set; }
        public Nullable<int> notaVideo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LlevaModel> Llevas { get; set; }
    }
}
